<?php

namespace App\Services;

use App\Data\Sandbox;
use Illuminate\Support\Facades\Http;

class GitHub
{
    /**
     * Posts a deployment notice on the pull request that triggered the deployment.
     */
    public static function postCreateDetails(): void
    {
        $sandbox = new Sandbox;
        $serverId = config('forge.server');
        $siteId = $sandbox->getSite()->id;
        $forgeLink = "https://forge.laravel.com/servers/$serverId/sites/$siteId";
        $phpVersion = config('forge.php_version');
        $webRoot = config('forge.web_directory');

        $message = <<<EOT
    # Blacksmith Sandbox Details
    A sandbox for this pull request was just provisioned by [Blacksmith](https://github.com/trendyminds/blacksmith-cli/). Details regarding your sandbox:
    | Info              | Details                                      |
    |-------------------|----------------------------------------------|
    | **URL**           | {$sandbox->fullUrl}                          |
    | **PHP Version**   | {$phpVersion}                                |
    | **Web Root**      | {$webRoot}                                   |
    EOT;

        if ($sandbox->getDatabase()) {
            $message .= "\n";
            $message .= <<<EOT
    | **Database**          | `{$sandbox->databaseName}`                 |
    | **Database User**     | `forge`                                    |
    | **Database Password** | The default `forge` database password      |
    EOT;
        }

        $message .= <<<EOT

    ---

    This message was automatically generated by Blacksmith. For full sandbox details visit [your Forge site]($forgeLink).
    EOT;

        Http::withHeaders([
            'Accept' => 'application/vnd.github+json',
            'X-GitHub-Api-Version' => '2022-11-28',
            'Authorization' => 'Bearer '.config('forge.github_token'),
        ])->withUrlParameters([
            'endpoint' => 'https://api.github.com',
            'pr' => config('forge.pr_number'),
        ])
            ->post('{+endpoint}/repos/'.config('forge.repo').'/issues/{pr}/comments', [
                'body' => $message,
            ])->throw();
    }

    /**
     * Posts a destroy notice on the pull request that triggered the deployment.
     */
    public static function postDestroyDetails(): void
    {
        $sandbox = new Sandbox;

        $message = <<<EOT
    Your sandbox has been successfully decommissioned.\n
    EOT;

        if (config('forge.enable_db') && config('forge.backup_provider')) {
            $message .= "\n";
            $message .= <<<EOT
    In addition to closing out this sandbox the database `{$sandbox->databaseName}` has been backed up to your backup provider.\n
    EOT;
        }

        $message .= <<<EOT
    \n---\n
    This message was automatically generated by Blacksmith.
    EOT;

        Http::withHeaders([
            'Accept' => 'application/vnd.github+json',
            'X-GitHub-Api-Version' => '2022-11-28',
            'Authorization' => 'Bearer '.config('forge.github_token'),
        ])->withUrlParameters([
            'endpoint' => 'https://api.github.com',
            'pr' => config('forge.pr_number'),
        ])->post('{+endpoint}/repos/'.config('forge.repo').'/issues/{pr}/comments', [
            'body' => $message,
        ])->throw();
    }
}
