<?php

namespace App\Services;

use App\Data\Sandbox;
use Illuminate\Support\Facades\Http;

class GitHub
{
    /**
     * Posts a deployment notice on the pull request that triggered the deployment.
     */
    public static function postCreateDetails(): void
    {
        $sandbox = new Sandbox;
        $githubToken = config('github.token');
        $prNumber = config('github.pr_number');
        $forgeLink = "https://forge.laravel.com/servers/{$sandbox->server}/sites/{$sandbox->getSite()->id}";

        $message = <<<EOT
    # Blacksmith Sandbox Details
    A sandbox for this pull request was just provisioned by [Blacksmith](https://github.com/trendyminds/blacksmith-cli/). Details regarding your sandbox:
    | Info              | Details                                      |
    |-------------------|----------------------------------------------|
    | **URL**           | http://{$sandbox->getUrl()}                  |
    | **PHP Version**   | {$sandbox->php_version}                      |
    | **Web Root**      | {$sandbox->web_directory}                    |
    EOT;

        if ($sandbox->getDatabase()) {
            $message .= "\n";
            $message .= <<<EOT
    | **Database**          | `{$sandbox->getDatabase()->name}`          |
    | **Database User**     | `forge`                                    |
    | **Database Password** | The default `forge` database password      |
    EOT;
        }

        $message .= <<<EOT

    ---

    This message was automatically generated by Blacksmith. For full sandbox details visit [your Forge site]($forgeLink).
    EOT;

        Http::withHeaders([
            'Accept' => 'application/vnd.github+json',
            'X-GitHub-Api-Version' => '2022-11-28',
            'Authorization' => "Bearer $githubToken",
        ])->post("https://api.github.com/repos/{$sandbox->git_repo}/issues/$prNumber/comments", [
            'body' => $message,
        ]);
    }
}
